package usermodel

var OwnerUserPrivileges = map[string]bool{
	"SignOut":                true,
	"RequestEmailChange":     true,
	"ConfirmEmailChange":     true,
	"RequestPhoneChange":     true,
	"ConfirmPhoneChange":     true,
	"GetProfile":             true,
	"GetProfileThumbnails":   true,
	"UpdateProfile":          true,
	"DeleteAccount":          true,
	"GetOnboardingStatus":    true,
	"AddAlternativeUserRole": true,
	"GetUserRoles":           true,
	"SwitchUserRole":         true,
	"GoHome":                 true,
	"UpdateOptStatus":        true,
	"GetPhotoUploadURL":      true,
}

var OwnerListingPrivileges = map[string]bool{
	"GetAllListings":   true,
	"GetOptions":       true,
	"StartListing":     true,
	"UpdateListing":    true,
	"EndUpdateListing": true,
	"GetListingStatus": true,
	"ApproveListing":   true,
	"RejectListing":    true,
	"SuspendListing":   true,
	"ReleaseListing":   true,
	"DeleteListing":    true,
	"CopyListing":      true,
	"ApproveVisting":   true,
	"RejectVisting":    true,
	"ApproveOffer":     true,
	"RejectOffer":      true,
	"EvaluateRealtor":  true,
	"SearchListing":    true,
	"GetListing":       true,
	"GetAllVisits":     true,
	"GetVisits":        true,
	"GetAllOffers":     true,
	"GetOffers":        true,
}

var RealtorUserPrivileges = map[string]bool{
	"SignOut":                true,
	"RequestEmailChange":     true,
	"ConfirmEmailChange":     true,
	"RequestPhoneChange":     true,
	"ConfirmPhoneChange":     true,
	"VerifyCreciImages":      true,
	"GetProfile":             true,
	"GetProfileThumbnails":   true,
	"UpdateProfile":          true,
	"DeleteAccount":          true,
	"GetOnboardingStatus":    true,
	"AddAlternativeUserRole": true,
	"GetUserRoles":           true,
	"SwitchUserRole":         true,
	"AcceptInvitation":       true,
	"RejectInvitation":       true,
	"GetAgencyOfRealtor":     true,
	"DeleteAgencyOfRealtor":  true,
	"GoHome":                 true,
	"UpdateOptStatus":        true,
	"GetPhotoUploadURL":      true,
	"GetCreciUploadURL":      true,
}

var RealtorListingPrivileges = map[string]bool{
	"ShareListing":          true,
	"GetFavoriteListings":   true,
	"AddFavoriteListing":    true,
	"RemoveFavoriteListing": true,
	"RequestVisit":          true,
	"ConfirmVisitDone":      true,
	"EvaluateOwner":         true,
	"CreateOffer":           true,
	"UpdateOffer":           true,
	"SendOffer":             true,
	"SearchListing":         true,
	"GetListing":            true,
	"GetAllVisits":          true,
	"GetVisits":             true,
	"GetAllOffers":          true,
	"GetOffers":             true,
}

var AgencyUserPrivileges = map[string]bool{
	"SignOut":              true,
	"RequestEmailChange":   true,
	"ConfirmEmailChange":   true,
	"RequestPhoneChange":   true,
	"ConfirmPhoneChange":   true,
	"GetProfile":           true,
	"GetProfileThumbnails": true,
	"UpdateProfile":        true,
	"DeleteAccount":        true,
	"GetOnboardingStatus":  true,
	"InviteRealtor":        true,
	"GetRealtorsByAgency":  true,
	"GetRealtorByID":       true,
	"UpdateRealtorByID":    true,
	"DeleteRealtorByID":    true,
	"GoHome":               true,
	"UpdateOptStatus":      true,
	"GetPhotoUploadURL":    true,
}
