global:
  scrape_interval: 5s  # Intervalo de scrape para todas as configurações

scrape_configs:
  - job_name: 'prometheus'  # Para monitorar o próprio Prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'toq_server'  # Para obter métricas sobre os alvos do toq_server
    static_configs:
      - targets: ['172.17.0.1:4318']  # IP da interface docker0

  - job_name: 'mysql_exporter'  # Para obter métricas sobre os alvos do MySQL Exporter
    static_configs:
      - targets: ['mysql_exporter:9104']