# Grafana Datasource Configuration for Prometheus and Traces
# This file configures datasources in Grafana
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    basicAuth: false
    jsonData:
      httpMethod: POST
      queryTimeout: 60s
      timeInterval: 15s

  # Jaeger datasource for distributed tracing
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://toq_server-jaeger-1:16686
    editable: true
    jsonData:
      httpMethod: GET

  # OpenTelemetry datasource for traces (alternative)
  - name: OpenTelemetry
    type: grafana-opentelemetry-datasource
    access: proxy
    url: http://otel-collector:4317
    editable: true
    jsonData:
      httpMethod: POST
